const rawTarih = [
    { text: "Uygurlar, Maniheizm dinini benimseyerek yerleşik hayata geçen ilk Türk devletidir.", answer: true, explanation: "Bu din değişikliği ile Türklerde mimari ve tarım gelişmiştir." },
    { text: "İslamiyet öncesi Türklerde 'Kut' anlayışı egemenliğin ilahi kaynaklı olduğuna inanmaktır.", answer: true, explanation: "Gök Tanrı tarafından hükümdara verildiğine inanılır." },
    { text: "Malazgirt Savaşı (1071) Anadolu'nun kapılarını Türklere açmıştır.", answer: true, explanation: "Alp Arslan komutasındaki Selçuklular Bizans'ı yenmiştir." },
    { text: "Osmanlı Devleti'nde ilk altın para Kanuni Sultan Süleyman döneminde basılmıştır.", answer: false, explanation: "İlk altın para (Sultani) Fatih Sultan Mehmet döneminde basılmıştır." },
    { text: "Lozan Antlaşması 24 Temmuz 1923 tarihinde imzalanmıştır.", answer: true, explanation: "Türkiye Cumhuriyeti'nin tapu senedi olarak kabul edilir." },
    { text: "Sivas Kongresi bölgesel toplanmış ancak ulusal kararlar almıştır.", answer: false, explanation: "Sivas Kongresi hem toplanış hem karar bakımından ulusaldır." },
    { text: "İstiklal Marşı, I. İnönü Savaşı'ndan sonra kabul edilmiştir.", answer: true, explanation: "12 Mart 1921 tarihinde kabul edilmiştir." },
    { text: "Osmanlı Devleti'nde ilk matbaa Lale Devri'nde kurulmuştur.", answer: true, explanation: "İbrahim Müteferrika ve Said Efendi tarafından 1727'de kuruldu." },
    { text: "Saltanat 1924 yılında kaldırılmıştır.", answer: false, explanation: "Saltanat 1 Kasım 1922'de kaldırılmıştır." },
    { text: "Ankara, 13 Ekim 1923'te Türkiye'nin başkenti ilan edilmiştir.", answer: true, explanation: "Cumhuriyet ilan edilmeden hemen önce başkent olmuştur." },
    { text: "Osmanlı'da sadrazamın mührüne 'Tuğra' denir.", answer: false, explanation: "Tuğra padişahın imzasıdır. Sadrazam 'Mühr-ü Hümayun' taşır." },
    { text: "Kutadgu Bilig, Kaşgarlı Mahmut tarafından yazılmıştır.", answer: false, explanation: "Yusuf Has Hacib tarafından yazılmıştır. Kaşgarlı Mahmut'un eseri Divanü Lügati't Türk'tür." },
    { text: "Miryokefalon Savaşı ile Anadolu'nun Türk yurdu olduğu kesinleşmiştir.", answer: true, explanation: "Bizans'ın Anadolu'yu geri alma ümidi tamamen sönmüştür." },
    { text: "Tanzimat Fermanı (1839) ile hukuk üstünlüğü ilkesi kabul edilmiştir.", answer: true, explanation: "Padişah kendi yetkilerinin üzerinde kanun gücünü tanımıştır." },
    { text: "Amasya Genelgesi ile Milli Mücadele'nin yöntemi belirlenmiştir.", answer: true, explanation: "'Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır.'" },
    { text: "Osmanlı'nın son padişahı Vahdettin (VI. Mehmet)'tir.", answer: true, explanation: "Saltanat kaldırıldıktan sonra ülkeden ayrılmıştır." },
    { text: "Erzurum Kongresi'ne Mustafa Kemal başkanlık etmiştir.", answer: true, explanation: "Kongrede Temsil Heyeti oluşturulmuştur." },
    { text: "Mondros Ateşkes Antlaşması 30 Ekim 1918'de imzalanmıştır.", answer: true, explanation: "Osmanlı Devleti fiilen sona ermiştir." },
    { text: "Kıbrıs Barış Harekatı 1974 yılında gerçekleştirilmiştir.", answer: true, explanation: "Ayşe tatile çıksın parolasıyla başlatılmıştır." },
    { text: "II. Meşrutiyet 1908 yılında ilan edilmiştir.", answer: true, explanation: "İttihat ve Terakki'nin baskısı sonucu ilan edilmiştir." },
    { text: "Karlofça Antlaşması ile Osmanlı ilk kez büyük çapta toprak kaybetmiştir.", answer: true, explanation: "1699 yılında imzalanmıştır." },
    { text: "Halifelik 1 Kasım 1922'de kaldırılmıştır.", answer: false, explanation: "Halifelik 3 Mart 1924'te kaldırılmıştır." },
    { text: "Dumlupınar Meydan Muharebesi 'Başkomutanlık Meydan Muharebesi' olarak da bilinir.", answer: true, explanation: "30 Ağustos zaferinin kazanıldığı savaştır." },
    { text: "Mudanya Ateşkesi ile İstanbul savaşılmadan kurtarılmıştır.", answer: true, explanation: "Diplomatik bir zaferdir." },
    { text: "İlk Türk devletlerinde devlet meselelerinin görüşüldüğü yere 'Kurultay' denir.", answer: true, explanation: "Toy veya Kengeş olarak da adlandırılır." },
    { text: "Osmanlı'da yeniçeri ocağını II. Mahmut kaldırmıştır.", answer: true, explanation: "Bu olaya Vaka-i Hayriye denir." },
    { text: "Sakarya Meydan Muharebesi sonrası M. Kemal'e 'Gazi' unvanı verilmiştir.", answer: true, explanation: "Ayrıca 'Mareşal' rütbesi de verilmiştir." },
    { text: "Atatürk İlkeleri anayasaya 1937 yılında girmiştir.", answer: true, explanation: "1924 Anayasası'nda yapılan değişiklikle eklenmiştir." },
    { text: "Hattı müdafaa yoktur, sathı müdafaa vardır sözü Sakarya'da söylenmiştir.", answer: true, explanation: "Topyekün savaş stratejisinin simge cümlesidir." },
    { text: "Osmanlı'da veraset sisteminde ilk değişikliği I. Murat yapmıştır.", answer: true, explanation: "Ülke padişah ve oğullarınındır anlayışını getirmiştir." },
    { text: "İstiklal Mahkemeleri sürekli görev yapan mahkemelerdir.", answer: false, explanation: "Sadece ihtiyaç duyulan dönemlerde kurulmuş geçici mahkemelerdir." },
    { text: "Takrir-i Sükun Yasası Şeyh Sait İsyanı üzerine çıkarılmıştır.", answer: true, explanation: "1925 yılında düzeni sağlamak için çıkarıldı." },
    { text: "Menemen Olayı bir rejim karşıtı isyandır.", answer: true, explanation: "Cumhuriyet ve devrimlere karşı çıkmıştır (1930)." },
    { text: "Boğazlar Komisyonu Montrö ile kaldırılmıştır.", answer: true, explanation: "1936 Montrö Boğazlar Sözleşmesi ile tam egemenlik sağlanmıştır." },
    { text: "Hatay 1939 yılında ana vatana katılmıştır.", answer: true, explanation: "M. Kemal'in vefatından kısa süre sonra gerçekleşmiştir." },
    { text: "I. Dünya Savaşı'nda Osmanlı'nın taarruz cepheleri Kafkas ve Kanal'dır.", answer: true, explanation: "Kalanlar savunma veya yardım cepheleridir." },
    { text: "Vaka-i Vakvakiye IV. Mehmet döneminde gerçekleşen bir asker isyanıdır.", answer: true, explanation: "Çınar Vakası olarak da bilinir." },
    { text: "Padişahın yetkilerinin ilk kez kısıtlandığı belge Sened-i İttifak'tır.", answer: true, explanation: "1808'de Ayanlar ile imzalanmıştır." },
    { text: "İnalcık'a göre Osmanlı'nın kuruluşu 1302 Koyunhisar Savaşı'dır.", answer: true, explanation: "Halil İnalcık bu tarihi bağımsızlık için baz alır." },
    { text: "Lale Devri Pasarofça Antlaşması ile başlar.", answer: true, explanation: "Patrona Halil İsyanı ile sona erer." },
    { text: "İlk Türk dünyası sözlüğü olan Divanü Lügati't Türk Arapça yazılmıştır.", answer: false, explanation: "Araplara Türkçe öğretmek amacıyla yazılmış, Türkçe sözlüktür." },
    { text: "Preveze Deniz Zaferi ile Akdeniz bir Türk gölü haline gelmiştir.", answer: true, explanation: "Barbaros Hayrettin Paşa komutasında kazanılmıştır." },
    { text: "Bağdat Fatihi olarak bilinen padişah IV. Murat'tır.", answer: true, explanation: "Revan ve Bağdat seferlerini yapmıştır." },
    { text: "Kabotaj Kanunu denizlerdeki egemenlik ile ilgilidir.", answer: true, explanation: "1 Temmuz 1926'da yürürlüğe girmiştir." },
    { text: "Saltanat Şurası Sevr Antlaşması'nı onaylayan kuruldur.", answer: true, explanation: "Mebusan Meclisi kapalı olduğu için bu kurul onaylamıştır." },
    { text: "Sadabat Paktı İtalya'nın yayılmacı politikasına karşı kurulmuştur.", answer: true, explanation: "Türkiye, İran, Irak ve Afganistan arasında (1937)." },
    { text: "Nutuk 1919-1927 yılları arasındaki olayları kapsar.", answer: true, explanation: "Samsun'a çıkışla başlar, Gençliğe Hitabe ile biter." },
    { text: "Osmanlı'da bütçe açığını kapatmak için 'Tarhuncu Bütçesi' yapılmıştır.", answer: true, explanation: "İlk modern bütçe denemesi kabul edilir." },
    { text: "Misak-ı Milli'den verilen ilk taviz Moskova Antlaşması'ndaki Batum'dur.", answer: true, explanation: "Gürcistan'a bırakılmıştır." },
    { text: "Türklerde ilk para Göktürkler döneminde basılmıştır.", answer: false, explanation: "Kendi adına para bastıran ilk Türk devleti Türgişler'dir (Baga Tarkan)." }
];

const rawCografya = [
    { text: "Türkiye'nin en uzun kıyı sınırı Karadeniz Bölgesi'ndedir.", answer: false, explanation: "Girinti-çıkıntıdan dolayı en uzun kıyı Ege Bölgesi'ndedir." },
    { text: "Dünyanın en fazla bor rezervine sahip ülkesi Türkiye'dir.", answer: true, explanation: "Dünya rezervlerinin %70'inden fazlası Türkiye'dedir." },
    { text: "Türkiye'nin en yüksek dağı Ağrı Dağı'dır.", answer: true, explanation: "5137 metre ile en yüksek zirvedir." },
    { text: "Tuz Gölü Türkiye'nin alanı en çok değişen gölüdür.", answer: true, explanation: "Derinliği az olduğu için buharlaşma ile alanı daralır." },
    { text: "Türkiye'de rüzgar erozyonu en çok İç Anadolu'da görülür.", answer: true, explanation: "Bitki örtüsü cılız ve arazi düz olduğu için." },
    { text: "Fön rüzgarları estiği yamacı serinletir.", answer: false, explanation: "Fön rüzgarları sürtünme nedeniyle her 100 metrede 1 derece ısınır." },
    { text: "Türkiye'nin en büyük delta ovası Çukurova'dır.", answer: true, explanation: "Seyhan ve Ceyhan nehirlerinin taşıdığı alüvyonlarla oluşmuştur." },
    { text: "Marmara Bölgesi'nde kümes hayvancılığı gelişmiştir.", answer: true, explanation: "Tüketici nüfusa yakınlık nedeniyle gelişmiştir." },
    { text: "Türkiye'nin en doğusu ile en batısı arasında 76 dakikalık zaman farkı vardır.", answer: true, explanation: "19 meridyen farkı vardır (19 x 4 = 76 dk)." },
    { text: "Güneydoğu Anadolu'da buharlaşma çok şiddetlidir.", answer: true, explanation: "Yaz sıcaklığı ve kuraklık nedeniyle." },
    { text: "Karadeniz kıyılarında orman alt sınırı 0 metreden başlar.", answer: true, explanation: "Nem ve yağışın bol olmasından dolayı." },
    { text: "Türkiye'de deprem riskinin en az olduğu yer Kuzey Anadolu Fay Hattı'dır.", answer: false, explanation: "KAF, Türkiye'nin en aktif ve riskli fay hattıdır." },
    { text: "Akdeniz ikliminin karakteristik bitki örtüsü Makidir.", answer: true, explanation: "Kısa boylu, bodur çalılar." },
    { text: "Rize'de turunçgil yetişmesi bir mikroklima örneğidir.", answer: true, explanation: "Çevresinden farklı iklim özelliği gösterdiği için." },
    { text: "Türkiye'de güneş enerjisinden yararlanma potansiyeli en az Karadeniz'dedir.", answer: true, explanation: "Bulutluluk oranının yüksek olması nedeniyle." },
    { text: "Maden çeşitliliğinin en fazla olduğu bölge Ege'dir.", answer: false, explanation: "En fazla Doğu Anadolu (Yukarı Fırat Bölümü) bölgesidir." },
    { text: "Türkiye 26-45 doğu meridyenleri arasındadır.", answer: true, explanation: "Türkiye'nin matematik konumudur." },
    { text: "Delta ovaları verimli tarım topraklarıdır.", answer: true, explanation: "Alüvyal topraklardan oluştukları için." },
    { text: "Türkiye'de sanayinin en gelişmiş olduğu il İstanbul'dur.", answer: true, explanation: "Ulaşım, sermaye ve pazarlama imkanları sayesinde." },
    { text: "Afşin-Elbistan'da linyit yatakları bulunur.", answer: true, explanation: "Türkiye'nin en büyük linyit rezervidir." },
    { text: "Toros Dağları kıvrımlı dağ sistemine örnektir.", answer: true, explanation: "Alp-Himalaya kuşağı içerisindedir." },
    { text: "Ege kıyılarında dağlar denize dik uzanır.", answer: true, explanation: "Bu nedenle kıyı ile iç kesim arası ulaşım kolaydır." },
    { text: "Türkiye'de aktif volkan bulunmamaktadır.", answer: true, explanation: "Sönmüş volkanlar vardır ancak aktif olan yoktur." },
    { text: "Van Gölü bir volkanik set gölüdür.", answer: true, explanation: "Nemrut lavlarının akarsu önünü kapatmasıyla oluşmuştur." },
    { text: "Türkiye'de nüfus dağılışı düzenlidir.", answer: false, explanation: "Yer şekilleri ve iklim nedeniyle kıyılarda toplanmıştır." },
    { text: "Bafra ve Çarşamba ovaları Samsun ilindedir.", answer: true, explanation: "Karadeniz'in en önemli deltalarıdır." },
    { text: "Zonguldak'ta taş kömürü çıkarılır.", answer: true, explanation: "I. jeolojik zaman arazisi olduğunu gösterir." },
    { text: "Türkiye'de yazları en sıcak yer Karadeniz'dir.", answer: false, explanation: "En sıcak yer Güneydoğu Anadolu'dur." },
    { text: "Bitlis'teki Nemrut Dağı ile Adıyaman'daki Nemrut Dağı aynıdır.", answer: false, explanation: "Bitlis'teki volkanik, Adıyaman'daki ise Kommagene krallığı kalıntıları olan turistik bir dağdır." },
    { text: "Kışın Türkiye'de en ılık yer Akdeniz kıyılarıdır.", answer: true, explanation: "Enlem ve denizellik etkisiyle." },
    { text: "Türkiye'de çay tarımı sadece Doğu Karadeniz'de yapılır.", answer: true, explanation: "Özel iklim ve toprak isteği nedeniyle." },
    { text: "Marmara Bölgesi'nde hidroelektrik potansiyeli çok yüksektir.", answer: false, explanation: "Ortalama yükselti az olduğu için potansiyel düşüktür." },
    { text: "Türkiye'de platoların geniş yer kaplaması epirojenez ile ilgilidir.", answer: true, explanation: "Anadolu'nun toptan yükselmesi (III. ve IV. zaman)." },
    { text: "Ege'de kıyı derinliği azdır.", answer: true, explanation: "Kıta sahanlığı geniştir." },
    { text: "Antalya'da seracılık çok gelişmiştir.", answer: true, explanation: "Kış ılıklığı ve güneşli gün sayısının fazlalığı nedeniyle." },
    { text: "Türkiye'de hayvancılıkta verimi artırmak için mera hayvancılığı yapılmalıdır.", answer: false, explanation: "Modern yöntem olan besi ve ahır hayvancılığı yapılmalıdır." },
    { text: "Bakır işletmesi Samsun'da bulunur.", answer: true, explanation: "Ulaşım (liman) imkanı nedeniyle kurulmuştur." },
    { text: "Muğla (Menteşe) yöresi dağlık olduğu için az nüfusludur.", answer: true, explanation: "Ana yollara sapa kaldığı için de gelişmemiştir." },
    { text: "GOP (Güneydoğu Anadolu Projesi) sadece tarımı hedefler.", answer: false, explanation: "Bölgesel kalkınmayı (eğitim, sağlık, enerji) hedefler." },
    { text: "Türkiye'nin en güney ucu Hatay (Beysun Köyü) dır.", answer: true, explanation: "36 derece kuzey paraleli üzerindedir." },
    { text: "Damlataş Mağarası karstik oluşumlu bir mağaradır.", answer: true, explanation: "Antalya-Alanya bölgesindedir." },
    { text: "Türkiye'de buğday hasadı en erken İç Anadolu'da yapılır.", answer: false, explanation: "Sıcaklıktan dolayı en erken Akdeniz'de yapılır." },
    { text: "Türkiye'nin en büyük adası Gökçeada'dır.", answer: true, explanation: "Çanakkale iline bağlıdır." },
    { text: "Yaz turizmi sezonu Karadeniz'de daha uzundur.", answer: false, explanation: "Yağış ve bulutluluk nedeniyle en kısadır." },
    { text: "Türkiye'de heyelan en çok Karadeniz Bölgesi'nde görülür.", answer: true, explanation: "Eğim, yağış ve killi toprak yapısı nedeniyle." },
    { text: "Jeotermal enerji potansiyeli en çok Ege'dedir.", answer: true, explanation: "Kırıklı (fay) yapı fazlalığı nedeniyle." },
    { text: "Bolu-Düzce çevresinde mobilya sanayisi gelişmiştir.", answer: true, explanation: "Hammadde (orman) yakınlığı nedeniyle." },
    { text: "Türkiye'de nüfusun en az olduğu yer Bayburt'tur.", answer: false, explanation: "Bayburt veya Tunceli arasında veriler yıla göre değişebilir." },
    { text: "Keban Barajı Fırat Nehri üzerindedir.", answer: true, explanation: "Türkiye'nin en büyük barajlarından biridir." },
    { text: "Karstik göller en çok Batı Toroslar'da bulunur.", answer: true, explanation: "Salda, Kestel, Avlan gibi göller örnektir." }
];

const mapData = {
    daglar: [
        { id: 1, name: "Ağrı Dağı", lat: 39.70, lng: 44.30 },
        { id: 2, name: "Erciyes Dağı", lat: 38.53, lng: 35.45 },
        { id: 3, name: "Uludağ", lat: 40.07, lng: 29.13 },
        { id: 4, name: "Süphan Dağı", lat: 38.93, lng: 42.82 },
        { id: 5, name: "Kaçkar Dağı", lat: 40.84, lng: 41.16 },
        { id: 6, name: "Hasan Dağı", lat: 38.13, lng: 34.16 },
        { id: 7, name: "Nur (Amanos) Dağları", lat: 36.75, lng: 36.33 }
    ],
    ovalar: [
        { id: 101, name: "Çukurova", lat: 36.85, lng: 35.32 },
        { id: 102, name: "Bafra Ovası", lat: 41.57, lng: 35.91 },
        { id: 103, name: "Çarşamba Ovası", lat: 41.35, lng: 36.71 },
        { id: 104, name: "Konya Ovası", lat: 37.88, lng: 32.48 },
        { id: 105, name: "Iğdır Ovası", lat: 39.92, lng: 44.04 }
    ],
    platolar: [
        { id: 201, name: "Haymana Platosu", lat: 39.43, lng: 32.49 },
        { id: 202, name: "Teke Platosu", lat: 36.60, lng: 30.00 },
        { id: 203, name: "Taşeli Platosu", lat: 36.50, lng: 33.00 },
        { id: 204, name: "Erzurum-Kars Platosu", lat: 40.40, lng: 42.60 },
        { id: 205, name: "Cihanbeyli Platosu", lat: 38.65, lng: 32.92 }
    ],
    goller: [
        { id: 301, name: "Van Gölü", lat: 38.63, lng: 42.90 },
        { id: 302, name: "Tuz Gölü", lat: 38.83, lng: 33.33 },
        { id: 303, name: "Beyşehir Gölü", lat: 37.75, lng: 31.50 },
        { id: 304, name: "Eğirdir Gölü", lat: 38.05, lng: 30.88 },
        { id: 305, name: "İznik Gölü", lat: 40.43, lng: 29.50 }
    ],
    sehirler: [
        { id: 401, name: "İstanbul", lat: 41.01, lng: 28.98 },
        { id: 402, name: "Ankara", lat: 39.93, lng: 32.86 },
        { id: 403, name: "İzmir", lat: 38.42, lng: 27.14 },
        { id: 404, name: "Antalya", lat: 36.90, lng: 30.71 },
        { id: 405, name: "Trabzon", lat: 41.00, lng: 39.72 },
        { id: 406, name: "Gaziantep", lat: 37.07, lng: 37.38 }
    ]
};
